version: '3.8' 
 
services: 
  postgres: 
    image: postgres:13 
    container_name: postgres 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: Final
   
    ports: 
      - "5432:5432" 
    healthcheck: 
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          retries: 5
          start_period: 30s
          timeout: 10s
      
  python: 
    build: ./python
    restart: on-failure
    container_name: my_python 
    depends_on: 
      postgres: 
           condition: "service_healthy"
    environment: 
      - POSTGRES_DB=Final
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password 
      - POSTGRES_HOST=postgres 
    volumes: 
      - ./python:/app 
    command: ["python", "/app/app.py"]
